spring:
  h2:
    console:
      enabled: true

  datasource:
# https://lob-dev.tistory.com/13
    url: jdbc:h2:tcp://localhost/~/homedoc
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
        show_sql: false
    defer-datasource-initialization: true

jwt:
  access-secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  access-token-validity-time: 180000
  refresh-secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  refresh-token-validity-time: 60480000

#logging:
#  level:
#    org.hibernate.SQL: info

decorator:
  datasource:
    p6spy:
      enable-logging: true
      log-format: "%(currentTime) | %(category) | %(sql)"
